
db.createCollection( 'Publicacions', {validator: {$jsonSchema: {bsonType: 'object',title:'Publicacions',required: [         'IDPublicacio',          'Visibilitat',          'Publicat',          'Video',          'Nº Comentaris'],properties: {IDPublicacio: {bsonType: 'objectId'},Visibilitat: {enum: "Publica", "Oculta", "Privada"},Publicat: {bsonType: 'bool'},Video: {bsonType: 'object',
title:'object',required: [         'IDVideo',          'Titol',          'Autor',          'Nº Reproduccions',          'Likes',          'Dislikes'],properties: {IDVideo: {bsonType: 'objectId'},Titol: {bsonType: 'string'},Autor: {bsonType: 'object',
title:'object',required: [         'IDUsuari',          'Nom Usuari',          'Email',          'Password',          'Data Naixament',          'Pais',          'Codi Postal'],properties: {IDUsuari: {bsonType: 'objectId'},Nom Usuari: {bsonType: 'string'},Email: {bsonType: 'string'},Password: {bsonType: 'string'},Data Naixament: {bsonType: 'date'},Sexe: {enum: "M", "F", "NB", "A", "T", "Altres"},Pais: {bsonType: 'string'},Codi Postal: {bsonType: 'int'}}},Nº Reproduccions: {bsonType: 'int'},Subscriptors: {bsonType: 'array',items: {
title:'object',required: [         'IDUsuari',          'Nom Usuari',          'Email',          'Password',          'Data Naixement',          'Pais',          'Codi Postal'],properties: {IDUsuari: {bsonType: 'objectId'},Nom Usuari: {bsonType: 'string'},Email: {bsonType: 'string'},Password: {bsonType: 'string'},Data Naixement: {bsonType: 'date'},Sexe: {enum: "M", "F", "NB", "A", "T", "Altres"},Pais: {bsonType: 'string'},Codi Postal: {bsonType: 'int'}}}},Etiquetes: {bsonType: 'array',items: {
title:'object',required: [         'IDEtiqueta',          'Nom'],properties: {IDEtiqueta: {bsonType: 'objectId'},Nom: {bsonType: 'string'}}}},Likes: {bsonType: 'int'},Dislikes: {bsonType: 'int'}}},Nº Comentaris: {bsonType: 'int'},Comentaris: {bsonType: 'array',items: {
title:'object',required: [         'IDComentari',          'Usuari',          'Text Comentari',          'Data Comentari',          'Likes',          'Dislikes'],properties: {IDComentari: {bsonType: 'objectId'},Usuari: {bsonType: 'object',
title:'object',required: [         'IDUsuari',          'Nom Usuari',          'Email',          'Password',          'Data Naixement',          'Pais',          'Codi Postal'],properties: {IDUsuari: {bsonType: 'objectId'},Nom Usuari: {bsonType: 'string'},Email: {bsonType: 'string'},Password: {bsonType: 'string'},Data Naixement: {bsonType: 'date'},Sexe: {enum: "M", "F", "NB", "A", "T", "Altres"},Pais: {bsonType: 'string'},Codi Postal: {bsonType: 'int'}}},Text Comentari: {bsonType: 'string'},Data Comentari: {bsonType: 'date'},Likes: {bsonType: 'int'},Dislikes: {bsonType: 'int'},Respostes: {bsonType: 'array',items: {
title:'object',required: [         'IDComentari',          'Usuari',          'Text Resposta',          'Data Resposta',          'Likes',          'Dislikes'],properties: {IDComentari: {bsonType: 'objectId'},Usuari: {bsonType: 'object',
title:'object',required: [         'IDUsuari',          'Nom Usuari',          'Email',          'Password',          'Data Naixement',          'Pais',          'Codi Postal'],properties: {IDUsuari: {bsonType: 'objectId'},Nom Usuari: {bsonType: 'objectId'},Email: {bsonType: 'objectId'},Password: {bsonType: 'objectId'},Data Naixement: {bsonType: 'date'},Sexe: {enum: "M", "F", "NB", "A", "T", "Altres"},Pais: {bsonType: 'objectId'},Codi Postal: {bsonType: 'int'}}},Text Resposta: {bsonType: 'string'},Data Resposta: {bsonType: 'date'},Likes: {bsonType: 'int'},Dislikes: {bsonType: 'int'}}}}}}},Playlist: {bsonType: 'object',
title:'object',required: [         'IDPlaylist',          'Nom'],properties: {IDPlaylist: {bsonType: 'objectId'},Nom: {bsonType: 'string'},Videos: {bsonType: 'array',items: {
title:'object',required: [         'IDVideo',          'Titol'],properties: {IDVideo: {bsonType: 'objectId'},Titol: {bsonType: 'string'}}}}}}}         }      }});  